import Testing

@testable import Views

/// The loading indicator's wireframe is generated by pure, deterministic
/// geometry (an icosahedron → freq-2 icosphere → its Goldberg-polyhedron dual).
/// A wrong face index or a broken subdivision would silently yield a malformed
/// sphere that still "renders", so the invariants are asserted directly.
@Suite("Geodesic loading-indicator geometry")
struct GeodesicGeometryTests {
    private func length(_ v: Vertex3D) -> Double {
        (v.x * v.x + v.y * v.y + v.z * v.z).squareRoot()
    }

    private func distance(_ a: Vertex3D, _ b: Vertex3D) -> Double {
        ((a.x - b.x) * (a.x - b.x) + (a.y - b.y) * (a.y - b.y) + (a.z - b.z) * (a.z - b.z))
            .squareRoot()
    }

    @Test("dual of the freq-2 icosphere has exactly 120 edges")
    func edgeCount() {
        // 80 triangles → 120 manifold edges → 120 dual struts. Any other count
        // means the face list or subdivision is broken.
        #expect(GeodesicGeometry.edges.count == 120)
    }

    @Test("every strut endpoint lies on the unit sphere")
    func verticesOnUnitSphere() {
        for (a, b) in GeodesicGeometry.edges {
            #expect(abs(length(a) - 1) < 1e-9)
            #expect(abs(length(b) - 1) < 1e-9)
        }
    }

    @Test("no strut is degenerate — endpoints are distinct")
    func noDegenerateEdges() {
        for (a, b) in GeodesicGeometry.edges {
            #expect(distance(a, b) > 1e-6)
        }
    }
}
